### ISSUE TITLE
[Bug] Incremental runs cause null daily_history fields when issue is updated after being Closed for 30 days

### ISSUE THREAD

**Issue by kenzie-marsh** [fivetran/dbt_jira#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When issues have had Status = Closed for 30+ days and are then updated, all columns other than `date_day, issue_id, issue_day_id` on the `jira__daily_issue_field_history` table become null. Since the most recent date for the issue receives all null values, the `jira__issue_enhanced` table is updated to all null values for that issue as well. Full-refresh-ing the package fixes this problem by creating a row for every date_day in between the updates. 

Related Slack thread: https://getdbt.slack.com/archives/C01D1R2JLLA/p1681241427533479

### Relevant error log or model output

```shell
Screenshot of problematic output included below.
```

### Expected behavior

The daily table should record the new/current values of all fields on an issue regardless of how long it has been Closed for when a field is updated. The daily table does not need to include a row for every issue_date_day after an issue has been Closed for 30+ days, but if it is updated again, then it should record a new date_day row with the newly updated field values. 

After the update, it does not need to record the next 30 days unless the issue was re-opened (but whatever you all think is best in this case works for me). 

### dbt Project configurations

```
version: '1.3.1'
config-version: 2
```

```
  jira:
    schema: dbt
  jira_source:
    schema: dbt_stg
```

```
  jira_database: raw
  jira_schema: jira 

  jira:
    issue_field_history_columns: [
      'Affects versions'
      ,'Approved By'
      ,'Assignee'
      ,'Battery Serial Number'
      ,...
      ,'Zip Number'
     ]
```

### Package versions

```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.0

  - package: fivetran/jira
    version: [">=0.13.0", "<0.14.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

```
Core:
  - installed: 1.3.1
  - latest:    1.5.0 - Update available!
```

### Additional Context

Example of problematic output: <img width="875" alt="image" src="https://github.com/fivetran/dbt_jira/assets/109629928/422395ed-99fc-4472-810d-f943805b8ecf">

Corresponding issue's history in the Jira UI: 
<img width="1412" alt="Screen Shot 2023-05-11 at 2 27 25 PM" src="https://github.com/fivetran/dbt_jira/assets/109629928/ddbfba7a-3145-4680-be6a-9214b73c92c5">

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @kenzie-marsh thanks so much for opening this issue!

I believe I have an understanding of what may be occurring here. I will plan to do some more investigating, but my team and I will be sure to pick this up at the start of our next sprint (next Wed) and will be sure to share updates as we work through addressing the bug.

Thanks again!

**Comment by fivetran-joemarkiewicz** [comment]
This bugfix is now live in the v0.14.0 release of the Jira package! As such, I will close out this issue. Please feel free to reopen if the issue persists after upgrading.

Thanks again for all your help @kenzie-marsh!
