### ISSUE TITLE
Casting To INT64 Line causing test failure

### ISSUE THREAD

**Issue by KishGoh99** [fivetran/dbt_jira#110]
We have a data product that brings in an external package - `DBT FiveTran Jira`  but the line in the model below fails in our run instance because it is trying to cast a string value into an integer. I began to explore and it turns out our piece of data that offends the line is a URL link that can have a string value.

https://github.com/fivetran/dbt_jira/blob/688a1ab627d17784a0efa7cc0eb1fac861cec99b/models/intermediate/int_jira__issue_epic.sql#L15

Is there a way to disable this test? or modify the line to accept string values?

<img width="1891" alt="Screenshot 2023-10-03 at 11 21 33" src="https://github.com/fivetran/dbt_jira/assets/146829454/158691ff-75fd-4e09-aa75-473a03408b66">

Thanks, Kishen

**Comment by fivetran-catfritz** [comment]
Hi @KishGoh99 thank you for submitting this issue. I am looking into this issue and have a question first. In your source data warehouse, do you have a jira table called `epic`? This is an optional table, and I'm wondering if it changes something our package does not anticipate. 

In the meantime, there are a couple ways to turn off the test. You mentioned using a data product, so I'm not sure which would work best for you. Are you running dbt via CLI, cloud, or another way?

**Comment by fivetran-catfritz** [comment]
Hi @KishGoh99 just checking in if you were able to look into this?

**Comment by andrew-karcher** [comment]
@KishGoh99 - We are facing this error now as well. It started in the last couple weeks I think. Did you figure out any workaround? or @fivetran-catfritz  did you find out anything?
