### ISSUE TITLE
[Bug] Issue Field History Incremental Load Missing Rows

### ISSUE THREAD

**Issue by eli-reber** [fivetran/dbt_jira#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The incremental load for the issue field history tables seems to be missing history for less than 1% of Jira issues.  The missing records begin on the date the Jira issues was created.  Updates that occur to fields that we are tracking do cause the Jira issue to then show up in the jira__daily_issue_field_history table, but there will only be records for the days after the update was made.

Note - A full refresh always resolves this problem.

Example for a Jira issue created on March 25th, and updated on March 27th. Our pipeline ran every day during this period, and there were no failures.

jira__daily_issue_field_history:

![Screenshot 2024-03-31 at 7 04 32 PM](https://github.com/fivetran/dbt_jira/assets/165606369/ecd5bcdb-4939-4ca4-bc03-6be1c50a6785)

All of the intermediate tables only contain data from March 27th onward. I won't post all of them for brevity, but here is int_jira_combine_field_histories:

![Screenshot 2024-03-31 at 7 20 28 PM](https://github.com/fivetran/dbt_jira/assets/165606369/b22bd54c-47f4-468e-92c1-ce4d487b1860)

All of the records are contained in our data lake source that is being queried, and the correct result (all history) appears when I run the compiled query for int_jira_combine_field_histories.

### Expected behavior

It is expected that there would be a row present for each day the issue has been open.

### dbt Project configurations

  jira:
    +schema: jira
    intermediate:
      +schema: jira
      int_jira__issue_epic:
        +enabled: false
    jira__daily_issue_field_history:
      +enabled: false

  jira_source:
    +schema: jira
    stg_jira__project:
      +enabled: false
    stg_jira__issue:
      +enabled: false

  jira_issue_history_buffer: 1200
  issue_field_history_columns:
    - Parent Link
    - Resolution
    - Reporter
    - Assignee
    - Project
    - Creator
    - Priority
    - Team
    - Epic Link
    - Description
    - Summary
    - Story Points
    - Original Estimate
    - Σ Original Estimate
    - Remaining Estimate
    - Σ Remaining Estimate
    - Time Spent
    - Σ Time Spent
    - Work Ratio
    - Due date
    - Labels
    - Bug Severity
    - Production Bug?
    - Escaped Bug?
    - Bug Origin
    - Bug Scope
    - Bug Priority
    - Last Viewed
    - Resolved
    - Updated
    - Status Category Changed
    - Created
    - Epic Category
    - Theme
    - Scope Change
    - Quarter
    - Original Target Date
    - Latest Target Date
    - DevOps Story Points
    - T-Shirt Size
    - UX Required?
    - Request Origin
    - X-Delivery Teams
    - Cross Teams
    - Security Review Required
    - CCB Category Level
  jira_using_sprints: false

### Package versions

  - package: fivetran/jira
    version: [">=0.15.0", "<0.16.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.7

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [x] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-avinash** [comment]
Hello @eli-reber ! Thank you for raising this issue with us, we were able to reproduce a version of this locally so it is definitely something we will need to account for in our models.

After some investigation, we believe [that a feature that will introduce lookback windows for incremental models](https://github.com/fivetran/dbt_jira/issues/117) could potentially solve this issue. We are working on that issue this sprint, and once we have a branch in a ready state we would love for you to test it out! 

We will keep you in the loop for any future developments. Let us know if you have any questions or thoughts!

**Comment by eli-reber** [comment]
Thank you for the update!  I'd be happy to help test your branch when you're ready, just let me know.

**Comment by fivetran-catfritz** [comment]
Hi @eli-reber I have a working test branch that incorporates the lookback window @fivetran-avinash mentioned, which you can install using the branch below. I'll also note that the main purpose of my updates is to help performance in addition to data quality, so I'd be interested in any feedback you have from that perspective as well!

```yml
  - git: https://github.com/fivetran/dbt_jira.git
    revision: feature/performance-enhancement
    warn-unpinned: false
```

**Comment by fivetran-catfritz** [comment]
Hi @eli-reber this update has been released in the latest version, which can be installed with the below snipped. 
```yml
packages:
  - package: fivetran/jira
    version: [">=0.17.0", "<0.18.0"]
```
I am closing out this issue, but feel free to ping us in this thread with any additional comments or questions!
