### ISSUE TITLE
Enhancement: Refactor int_jira__issue_calendar_spine

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_jira#15]
int_jira__issue_calendar_spine right now relies on `run_query`, which fails when you run `dbt compile` before `dbt run`.  

Look into how to address this issue, and push findings to our ZD and Hubspot packages as well as they use calendar spines/run queries.

**Comment by fivetran-joemarkiewicz** [comment]
The fix from this issue is now live within [Release v0.3.0](https://github.com/fivetran/dbt_jira/tree/v0.3.0).
