### ISSUE TITLE
Issue in jira__daily_issue_field_history when field changes several times a day

### ISSUE THREAD

**Issue by marie-aircall** [fivetran/dbt_jira#18]
Hi team,

I noticed an issue in jira__daily_issue_field_history whenever a field changes several times a day.
In the exemple below, we see that everything is well recorded in _int_jira__combine_field_histories_. However, in _int_jira__daily_field_history_, where we are supposed to only look at the latest value of each field for each day and each issue, there are still two instances of the Assignee field for the same day... That messes up the data of all following models and eventually of the jira__daily_issue_field_history model.

<img width="1159" alt="Capture d’écran 2021-04-07 à 11 44 49" src="https://user-images.githubusercontent.com/82089404/113846322-aa1f5200-9796-11eb-97a8-3b8143cbfc2c.png">

<img width="1158" alt="Capture d’écran 2021-04-07 à 11 46 53" src="https://user-images.githubusercontent.com/82089404/113846621-f5396500-9796-11eb-8fc1-6a4e525864f1.png">

Here's what I got after doing a full refresh of the models. The data is correct so I assume the issue comes from the incremental mode...

<img width="1157" alt="Capture d’écran 2021-04-07 à 12 21 37" src="https://user-images.githubusercontent.com/82089404/113851452-cffb2580-979b-11eb-9909-b5176613da3a.png">

Do you think you could help me on this?
Thanks a lot,
Have a great day!
Marie

**Comment by fivetran-jamie** [comment]
hey there, taking a look at this right now!

**Comment by fivetran-jamie** [comment]
what version of the package are you using by the way? i ask because v0.1.4 (we're on 0.1.5 now) addressed a bug with incremental runs _could_ be related to this

**Comment by marie-aircall** [comment]
Hey Jamie,
Thanks a lot for your help, indeed still on v0.1.4.

**Comment by fivetran-jamie** [comment]
hey @marie-aircall -- we just pushed out a release that should fix this issue! It should be up on dbt hub tomorrow or so, but if you'd like to try it out before then: 
```yml
# packages.yml
packages:
  - git: https://github.com/fivetran/dbt_jira.git
    revision: v0.2.0
```

let me know if the problem persists for you! and thank you so much again for surfacing this

**Comment by fivetran-jamie** [comment]
and it's on the hub now! https://hub.getdbt.com/fivetran/jira/latest/ 

closing the issue for now, please re-open if the problem persists 🙂
