### ISSUE TITLE
QUESTION - [issue when upgrading packages]

### ISSUE THREAD

**Issue by marie-aircall** [fivetran/dbt_jira#28]
**Are you a Fivetran customer?** 
Yes ! Marie Sergue, Data Analyst at Aircall

**Your Question**
I am trying to upgrade jira_source and jira packages but my CI test returns the following error: 
` Database Error in model int_jira__issue_calendar_spine (models/intermediate/field_history/int_jira__issue_calendar_spine.sql)
    Could not find parent table for alias "staging.ci_schema_stg_jira.stg_jira__issue".`

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
Not super urgent but it's blocking me from fixing issues that were supposed to be fixed by the new package version.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @marie-aircall thanks for opening this question! Is this error occurring when you execute `dbt compile` or `dbt run`?

**Comment by marie-aircall** [comment]
Hi! Thanks for your reply, it occurs when i execute dbt compile.

**Comment by fivetran-kristin** [comment]
@marie-aircall does this error persist if you first run `dbt run` and then run `dbt compile`?


Also, have you tried running `dbt run --full-refresh`?

**Comment by marie-aircall** [comment]
Hi Kristin,

Thanks for the advice, i managed to make it work!

Thanks for your help on this,
Marie
