### ISSUE TITLE
[Bug] Assignee names, reporter names, emails etc not appearing how they should 

### ISSUE THREAD

**Issue by jamienewcomb** [fivetran/dbt_jira#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

This does not look right to me. Don't think this is a me issue but do say if it is 

<img width="1517" alt="Screenshot 2022-09-27 at 17 36 08" src="https://user-images.githubusercontent.com/59560169/193039781-6a669cea-6a7a-4a52-9292-c94bab8e2def.png">
<img width="1677" alt="Screenshot 2022-09-27 at 17 29 58" src="https://user-images.githubusercontent.com/59560169/193039809-0b5622dd-9b19-4a1b-850b-d00909aa7d56.png">

### Expected behavior

Would expect to see the information aligned to the column names 

### dbt Project configurations

-

### Package versions

-

### What database are you using dbt with?

snowflake

### dbt Version

-

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jamienewcomb can you confirm that in the source table for `jira.user` those fields do not look like that? The `int_jira__issue_users` model (which I believe is what you are querying from) populates these fields by performing a join on the source table. 
https://github.com/fivetran/dbt_jira/blob/78c49634ffa891b376eb2b1c2675d6a3ba3867ce/models/intermediate/int_jira__issue_users.sql#L29-L43

I wouldn't believe this should cause any data quality issues, but curious to see what you say it looks like at the source.

**Comment by jamienewcomb** [comment]
Yeah the source table `JIRA_USER` looks like this aswell.

Feels odd that all the personal information is jumbled up but the surrounding fields are absolutely fine with the correct info. The user IDs are all correct aswell

**Comment by jamienewcomb** [comment]
Could Atlassian have done something here - which is what I am thinking

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jamienewcomb this may be a result of Snowflake column level hashing based on role permissions. You Snowflake admin may have restricted access to those columns based on the permissions of the role you are using.

I would reach out to your Snowflake admin and see if this is the case.

**Comment by jamienewcomb** [comment]
Thanks @fivetran-joemarkiewicz - that would make alot of sense. this feels like a me issue so gonna close for now while I check that and will reopen if we feel there is something else wrong
