### ISSUE TITLE
Disabling models

### ISSUE THREAD

**Issue by jacobadler-dutchie** [fivetran/dbt_jira#9]
We're erroring out on everything dependent on the sprint source table since we don't have a sprint table in our Fivetran-synced schema. Is there functionality built into this package to disable like Zendesk using_schedules: false?

**Comment by fivetran-kristin** [comment]
Hey @jacobadler-dutchie!  Thanks for the suggestion. I've implemented this change and it's ready for testing.  Can you take the following steps and see if this works properly for you?

1. Remove your current dependency on the Jira package, and instead declare a dependency on the working branch of this package.  In your `packages.yml` file:
```
packages:
  - git: https://github.com/fivetran/dbt_jira.git
    revision: create_comment_variable
    warn-unpinned: false 
```
    
2. In your `dbt_project.yml` file, disable the use of variables by adding the following:

```
vars:
  jira:
    include_comments: false
```

3. Run `dbt clean` to remove old package dependencies. 
4. Run `dbt deps`
5. Run `dbt run`

**Comment by jacobadler-dutchie** [comment]
Thanks Kristin! With `using_sprints: false` variable in dbt_project.yml, we're down to one error. That remaining error is because don't have a `board` table in our Jira schema. Do you think it makes sense to add one more variable here for that table?

**Comment by fivetran-kristin** [comment]
We actually just create a staging model for `board` and don't use it in any downstream models. I've removed that to keep things simple and not introduce another variable.  

Can you re-run on your end and see if the change fixed your remaining error?

**Comment by jacobadler-dutchie** [comment]
Hi Kristin, error-free for now. Thanks!

**Comment by fivetran-kristin** [comment]
Fantastic. This change is reflected in the latest version of the package.  You can upgrade by using the following in your packages.yml file:

```
packages:
  - package: fivetran/jira
    version: 0.1.2
```
